jobs:
    terraform:
        name: terraform CI
        runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: terraform plan
        uses: hashicorp/setup-terraform@v1
        id: plan
        run: |
          terraform init && terraform plan -out=check.tfplan && terraform show -json check.tfplan > check.tfplan.json
      
      - name: terraform-compliance
        uses: terraform-compliance/github_action@main
        with:
          plan: check.tfplan.json
          features: https://github.com/Bipin210/jenkins-example-terraform.git
