jobs:
    terraform:
        name: terraform CI
        runs-on: ubuntu-latest


    steps:
      - name: terraform-compliance
        uses: terraform-compliance/github_action@0.3.0

      - name: terraform plan
        id: plan
        run: |
          terraform init && terraform plan -out=check.tfplan && terraform show -json check.tfplan > check.tfplan.json
      
      - name: terraform-compliance
        uses: terraform-compliance/github_action@main
        with:
          plan: check.tfplan.json
          features: https://github.com/Bipin210/jenkins-example-terraform.git
