name: 'Terraform Complaiance and Integration Testing'

on:
  push:
    branches: [ main ]

jobs:
    terraform:
      runs-on: self-hosted

      steps:
      - uses: actions/checkout@v2
      - name: terraform plan
        id: plan
        run: |
          cd /home/bipin/jenkins-example-terraform/
          ls
          terraform init 
          terraform plan -out check.tfplan 
          terraform show -json check.tfplan > check.tfplan.json
      - name: terraform-compliance
        id: run
        run: |
          cd /home/bipin/jenkins-example-terraform/
          terraform-compliance -f . -p check.tfplan.json  
       
